version: "3.8"

services:
  web:
    image: yokowasis/rdm
    environment:
      - SERVICE_FQDN_RDM=${SERVICE_FQDN_RDM:-}
      - DB_HOST=db
      - DB_USERNAME=${DB_USER:-rdm}
      - DB_PASSWORD=${DB_PASS:-rdm}
      - DB_DATABASE=${DB_NAME:-rdm}
    depends_on:
      - db
    expose:
      - 80
    volumes:
      - uploads:/var/www/html/__uploads

  db:
    image: yokowasis/rdm-mysql:latest
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - SERVICE_FQDN_PMA=${SERVICE_FQDN_PMA:-}
      - PMA_HOST=db
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
    expose:
      - 8080
    depends_on:
      - db

volumes:
  db_data:
  uploads:
